# General settings
cluster_name: "my-fargate-cluster"
service_name: "my-fargate-service"
task_definition_name: "my-fargate-task"
container_name: "my-container2"
image_name: "my-docker-image:latest"
cpu: "256"
memory: "512"
region: "us-west-1"

# Networking
subnet_ids:
  - "subnet-xxxxxxxx"
  - "subnet-yyyyyyyy"
security_groups:
  - "sg-xxxxxxxxxx"

# IAM Role
execution_role_arn: "arn:aws:iam::437104085542:role/ecsTaskExecutionRole"

# Resource state (true for deletion, false for creation)
delete_resources: false
